filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /mbd/logs/misbehaviors.log
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

output.logstash:
  hosts: ["${LOGSTASH_URL:logstash:5044}"]

logging.level: info
logging.to_files: false
