FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends libexpat1 && rm -rf /var/lib/apt/lists/*
WORKDIR /MBD
RUN pip install --no-cache-dir matplotlib contextily
COPY replay-launcher.py replay.py ./
CMD ["python", "replay-launcher.py", "--es-url", "http://elasticsearch:9200"]
